version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Flask app
          command: |
            export FLASK_APP=main.py
            flask run --host=0.0.0.0

workflows:
  version: 2
  build-and-run:
    jobs:
      - build
