version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest

      - run:
          name: Build Docker image
          command: docker build -t welcome .

      - deploy:
          name: Deploy to server
          command: |
            docker run -d --zaid -p 5000:5000 welcome

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
