version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

     

      - run:
          name: Build Docker image
          command: docker build -t welcome .

      - deploy:
          name: Deploy to server
          command: |
            docker run -d --zaid -p 5000:5000 welcome

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
